[platformio]
src_dir = .

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
monitor_filters = log2file, colorize
monitor_rts = 0
monitor_dtr = 0

; ---------------------------------
; BROADCASTER CONFIGURATIONS
; ---------------------------------
[broadcaster_base]
build_src_filter = +<broadcaster/src/>
board_build.filesystem = littlefs
board_build.filesystem_dir = broadcaster/data
extra_scripts = broadcaster/frontend/build_web.py
lib_deps =
    ESP Async WebServer
    https://github.com/me-no-dev/AsyncTCP.git
lib_ignore =
    AsyncTCP_RP2040W

[env:broadcaster_wroom]
extends = env, broadcaster_base
board = mhetesp32minikit
board_build.flash_size = 4MB
board_build.partitions = broadcaster/partition_map.csv

[env:broadcaster_c3]
extends = env, broadcaster_base
board = esp32-c3-devkitm-1
board_build.partitions = broadcaster/partition_map.csv

; ---------------------------------
; LISTENER CONFIGURATIONS
; ---------------------------------
[listener_base]
build_src_filter = +<listener/src/>
lib_deps =
    fastled/FastLED@^3.6.0
    h2zero/NimBLE-Arduino@^1.4.1

[env:listener_wroom]
extends = env, listener_base
board = esp32dev

[env:listener_c3]
extends = env, listener_base
board = esp32-c3-devkitm-1
